// Removes Android permissions from release builds only (preview APK and production AAB).
//
// `android.blockedPermissions` in app.json removes a permission from every build,
// including the development build, which needs INTERNET to load JavaScript from the
// dev server. This plugin writes a release-only manifest
// (android/app/src/release/AndroidManifest.xml); Gradle's manifest merger applies it
// on top of the main manifest and the libraries' manifests for release builds.
//
// Usage in app.json: ["./plugins/withReleaseBlockedPermissions", ["android.permission.INTERNET"]]

const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

module.exports = function withReleaseBlockedPermissions(config, permissions = []) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'release');
      fs.mkdirSync(dir, { recursive: true });
      const lines = permissions.map((p) => `  <uses-permission android:name="${p}" tools:node="remove"/>`);
      fs.writeFileSync(
        path.join(dir, 'AndroidManifest.xml'),
        [
          '<?xml version="1.0" encoding="utf-8"?>',
          '<!-- Generated by plugins/withReleaseBlockedPermissions.js: permissions removed from release builds only. -->',
          '<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">',
          ...lines,
          '</manifest>',
          '',
        ].join('\n'),
      );
      return cfg;
    },
  ]);
};
